= Packer Windows Build

These files create a minimal Windows Server box for Windows Server 2022 Standard Core.

== Prerequisites and Usage

For this build the evaluation iso from Microsoft is used. To use this project

* clone it
* download https://www.microsoft.com/en-us/evalcenter/[Windos Server 2022 Evaluation]
* install/download https://www.packer.io/[packer]
* have a Windows OS on which Hyper-V is included and enable the feature
* ensure that the Windows Account used for the build is in the 'Hyper-V Administrators' group
* create an externe Hyper-V Switch connected to your external network adapter (in this example `extpacker` is used)
* download https://docs.microsoft.com/de-de/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7[PowerShell Core] and put as pwsh.msi in `cd` subfolder
* to build the CD containing the answer file (Floppy is not available in UEFI mode) install a CD build tool and ensure that it is included in your path
** I'm using https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install[oscdimg] as this is included in the Windows ADK used to create the answer file
* create an variables file, for example `windows.auto.pkrvars.hcl` containing the password for Administrator or set environment variable `PKR_VAR_winrm_password` containing the password
* change directory to `<repo-root>/packer`
* run `packer init windows` to install the Hyper-V plugin
* run `packer build windows`

Windows needs the password of `Administrator` (or any other user) within the `Autounattend.xml` file.
To inject this, a template `server-2022-standard-core.xml` is used to generate `Autounattend.xml` using the HCL function `templatefile` to replace the variable `admin_password`.
This file will be included on the `cd` that is build.

All files in `cd` will be included in a new iso file packer creates and mounts to the Hyper-V machine.

[IMPORTANT]
====
Using an external switch had slowed down my network upload speed horribly.
I needed to disable `Large Send Offload Version 2` for IPv4 and IPv6 on the Hyper-V Virtual Ethernet Adapter that was attached from my host OS to the virtual switch to fix that.
In addition network download speed inside the VM was very slow until `EnableSoftwareRsc` was set to `$false` on the external switch used.
====

== Settings

[NOTE]
====
All settings used except the Administrator password are hard coded to the HCL file.
====

To change settings adjust them in `windows-server-2022-standard-core.pkr.hcl` as needed.
