version: '3'

includes:
  ostask: ./Taskfile_{{OS}}.yml

vars:
  OSVERSION: 2019-datacenter-core
  UNATTEND_DIRECTORY: answers
  TEMPLATE_FILE: template.xml
  DEFAULTS_FILE: windows.auto.pkrvars.hcl

tasks:
  default:
    desc: Run the packer build stored in the current directory
    cmds:
      - task: ostask:generate-autounattended-xml
      - packer build -color=false -var-file={{.OSVERSION}}.pkrvars.hcl .
